package com.diginamic.magic.domain.enums;

public enum Mana {
    RED, BLUE, GREEN, WHITE, BLACK, RED_AND_BLUE, RED_AND_GREEN, RED_AND_WHITE, RED_AND_BLACK,
    BLUE_AND_GREEN, BLUE_AND_WHITE, BLUE_AND_BLACK, GREEN_AND_BLACK, GREEN_AND_WHITE, WHITE_AND_BLACK;
}